Shopping-bag/Models/ErrorViewModel.cs
using System;

namespace Shopping_bag.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Shopping-bag/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shopping_bag.Models
{
    public class Product
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public DateTime DateTime { get; set; }

        

        public Product(Guid id, string name, double price, DateTime dateTime)
        {
            Id = id;
            Name = name;
            Price = price;
            DateTime = dateTime;
        }
    }
}

Shopping-bag/Models/ShoppingBag.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shopping_bag.Models
{
    public class ShoppingBag
    {
        public Guid Id { get; set; }
        public ISet<ShoppingBagItem> Items { get; set; }
        public DateTime DateTime { get; set; }

        public ShoppingBag(Guid id)
        {
            Id = id;
            DateTime = DateTime.Now;
            Items = new HashSet<ShoppingBagItem>();
            
        }
    }
}

Shopping-bag/Models/ShoppingBagItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shopping_bag.Models
{
    public class ShoppingBagItem
    {
        public Guid Id { get; set; }
        public int amount { get; set; }
        public Product product { get; set; }
        public ShoppingBag shoppingBag { get; set; }
        public ShoppingBagItem(Guid id, int amount, Product product)
        {
            Id = id;
            this.amount = amount;
            this.product = product;
        }
    }
}

Shopping-bag/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Shopping_bag.Interfaces;
using Shopping_bag.Models;
using Shopping_bag.Services;
using Shopping_bag.ViewModel;

namespace Shopping_bag.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IProductService _productsService;
        public HomeController(ILogger<HomeController> logger, IProductService productService)
        {
            _logger = logger;
            _productsService = productService;
        }

        public async Task<IActionResult> Index()
        {


            ProductsListViewModel prodcutPageViewModel = new ProductsListViewModel()
            {
                Products = await _productsService.GetProducts(),
                title = "Produkty"
            };

            return View(prodcutPageViewModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Shopping-bag/Controllers/ShoppingBagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Shopping_bag.Interfaces;

namespace Shopping_bag.Controllers
{
    public class ShoppingBagController : Controller
    {
        private readonly IShoppingBagService _shoppingBag;
        private readonly IProductService _productService;

        public ShoppingBagController(IShoppingBagService shoppingBag, IProductService productService)
        {
            _shoppingBag = shoppingBag;
            _productService = productService;
        }

        public IActionResult AddToBag(Guid productId)
        {
            _shoppingBag.AddToCart(productId, 1);
            return Redirect(Request.GetTypedHeaders().Referer.ToString());
        }

        public IActionResult ShoppingBagItemsList()
        {
            var shoppingCartItems = _shoppingBag.GetShoppingCartItems();


            return View(shoppingCartItems);
        }
    }
}

Shopping-bag/Views/Home/Index.cshtml
@model ProductsListViewModel

<div class="text-center">
    <h1 class="display-4">
        <a 
           asp-controller="ShoppingBag"
           asp-action="ShoppingBagItemsList">
            @Model.title @await Component.InvokeAsync("ShoppingBagSummary")
        </a>        
    </h1>
    <div class="container">
        <div class="row">
            @foreach (var @product in Model.Products)
            {
                <div class="col-2">@product.Name <p>@product.Price</p>
            
                    <a class="btn btn-primary"
                    asp-controller="ShoppingBag"
                    asp-action="AddToBag"
                    asp-route-productId="@product.Id">Add to Cart</a>
                </div>
            }
        </div>
    </div>

</div>

Shopping-bag/Views/Shared/Components/ShoppingBagSummary/Default.cshtml
@model decimal

<p>@Model.ToString()</p>

Shopping-bag/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shopping_bag</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
            @RenderBody() 
</body>
</html>

Shopping-bag/Views/ShoppingBag/ShoppingBagItemsList.cshtml
@model ShoppingBag


<div class="text-center">
    <h1 class="display-4">Koszyk:</h1>
    <div class="container">
        <div class="row">
            @foreach (var @product in Model.Items)
            {
                <div class="col-2">
                    @product.product.Name <p> @product.amount</p>
                </div>
            }
        </div>
    </div>

</div>